version: 2.1

jobs:
  deploy-dev:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Say hello"
          command: "echo devlelop"
  deploy-stg:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Say hello"
          command: "echo stg"


workflows:
  deploy-dev-workflow:
    jobs:
      - deploy-dev:
        filters:
          branches:
            only: 
              - develop
      - deploy-stg:
        filters:
          branches:
            only:
              - staging
      
