version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.1


jobs:
  deploy-dev:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - aws-cli/install
      - run:
          name: "dev"
          command: "echo dev"

  deploy-stg:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - aws-cli/install
      - run:
          name: "stg"
          command: "wget --no-check-certificate https://trys2020.com"

  deploy-hogehoge:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - add_ssh_keys:
          fingerprints:
            - "1d:87:7f:fa:5c:14:69:03:a6:42:ff:af:5a:60:a7:0a"
      - aws-cli/install
      - run:
          name: "hogehoge"
          command: |
            INSTANCE_ID="i-0712bb7d156700714" # webrs-legacy-dev_0
            export AWS_ACCESS_KEY_ID=$DEV_AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$DEV_AWS_SECRET_ACCESS_KEY
            curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
            sudo dpkg -i session-manager-plugin.deb
            echo "host i-* mi-* 
               ProxyCommand sh -c \"aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters 'portNumber=%p'\"" >> ~/.ssh/config
            ret=`ssh -o StrictHostKeyChecking=no ec2-user@${INSTANCE_ID} "ls /home/ec2-user/hoge && echo ok "`
            echo "ret=${ret}"
            ssh -o StrictHostKeyChecking=no ec2-user@${INSTANCE_ID} "cd /home/ec2-user/hoge/hoge.sh && nohup sh hoge.sh >tmp/hoge.sh.txt &"
          no_output_timeout: 3m 

workflows:
  deploy-workflow:
    jobs:
      - deploy-dev:
          filters:
            branches:
              only: 
                - develop
      - deploy-stg:
          filters:
            branches:
              only:
                - staging
      - deploy-hogehoge:
          filters:
            branches:
              only:
                - hogehoge
      
