version: 2.1

jobs:
  deploy-dev:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "dev"
          command: "curl trys2020.com"
  deploy-stg:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "stg"
          command: "wget --no-check-certificate https://trys2020.com"


workflows:
  deploy-workflow:
    jobs:
      - deploy-dev:
          filters:
            branches:
              only: 
                - develop
      - deploy-stg:
          filters:
            branches:
              only:
                - staging
      
