version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.1


jobs:
  deploy-dev:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "dev"
          command: "echo dev"

  deploy-stg:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "stg"
          command: "wget --no-check-certificate https://trys2020.com"

  deploy-hogehoge:
    docker:
      - image: cimg/base:stable
    steps:
      - aws-cli/install
      - run:
          name: "hogehoge"
          command: "aws s3 ls"
 

workflows:
  deploy-workflow:
    jobs:
      - deploy-dev:
          filters:
            branches:
              only: 
                - develop
      - deploy-stg:
          filters:
            branches:
              only:
                - staging
      - deploy-hogehoge:
          filters:
            branches:
              only:
                - hogehoge
      
