version: 2.1

jobs:
  deploy-dev:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  deploy-dev-workflow:
    jobs:
      - deploy-dev:
        filters:
          branches:
            only: develop
      
